pipeline {
    agent any

    environment {
        PATH = "${env.PATH};C:\\Program Files\\Git\\bin"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/LloydCosta87/devops-23-24-JPE-1231838.git'
            }
        }
        stage('Assemble') {
            steps {
                sh 'bash -c "./gradlew assemble"'
            }
        }
        stage('Test') {
            steps {
                sh 'bash -c "./gradlew test"'
            }
            post {
                always {
                    junit '**/build/test-results/test/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
            }
        }
    }
}
