pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/LloydCosta87/devops-23-24-JPE-1231838.git'
            }
        }
        stage('Assemble') {
            steps {
                powershell './gradlew.bat assemble'
            }
        }
        stage('Test') {
            steps {
                powershell './gradlew.bat test'
            }
            post {
                always {
                    junit '**/build/test-results/test/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
            }
        }
    }
}
