pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/LloydCosta87/devops-23-24-JPE-1231838.git'
            }
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
            post {
                success {
                    junit '**/build/test-results/test/*.xml'
                }
            }
        }
        stage('Assemble') {
            steps {
                sh './gradlew assemble'
            }
            post {
                success {
                    archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
                }
            }
        }
    }
}
