version: '3'
services:

  db:
    image: lloydcosta/chatserver/db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/opt/h2/data
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      - H2_OPTIONS=-tcpAllowOthers -ifNotExists

  web:
    image: lloydcosta/chatserver/web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:9092/./jpadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  db_data:
